---
formatters:
  enable:
    - gofmt
    - goimports

linters:
  default: none

  enable:
    - dupl
    - gomodguard
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - thelper
    - unused
    - usestdlibvars

run:
  timeout: 10m

version: "2"
